# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clotho Hugo Theme"
license = "MIT"
licenselink = "https://github.com/genshinh/hugo-theme-clotho/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/genshinh/hugo-theme-clotho"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.54.0"

[author]
  name = "David Genshin Hammer"
  homepage = "https://github.com/genshinh"
